### ISSUE TITLE
JEST 5.3.4 incompatibility

### ISSUE THREAD

**Issue by aheritier** [VanRoy/spring-data-jest#84]
Spring boot 2.0.5 Upgraded JEST from 5.3.3 to 5.3.4

https://github.com/spring-projects/spring-boot/commit/bffc54240956c3ef8ccd1de2c24331a4a8115085

But JEST changed its `CreateIndex` API

https://github.com/searchbox-io/Jest/wiki/Changelog#-v534

Thus 

```
Caused by: java.lang.NoSuchMethodError: io.searchbox.indices.CreateIndex$Builder.settings(Ljava/lang/Object;)Lio/searchbox/indices/CreateIndex$Builder;
	at com.github.vanroy.springdata.jest.JestElasticsearchTemplate.createIndex(JestElasticsearchTemplate.java:193)
	at com.github.vanroy.springdata.jest.JestElasticsearchTemplate.createIndexWithSettings(JestElasticsearchTemplate.java:1440)
	at com.github.vanroy.springdata.jest.JestElasticsearchTemplate.createIndexIfNotCreated(JestElasticsearchTemplate.java:1425)
	at com.github.vanroy.springdata.jest.JestElasticsearchTemplate.createIndex(JestElasticsearchTemplate.java:177)
```

**Comment by DanielFran** [comment]
Looking at the changes: https://github.com/searchbox-io/Jest/compare/v5.3.3...v5.3.4

Seems related to this: https://github.com/searchbox-io/Jest/commit/ac23e66f9b834cb8fec4bb93ddb9995b9f29b670

**Comment by VanRoy** [comment]
Fixed in 3.1.5 released today.

Thanks both for your help.

**Comment by DanielFran** [comment]
@VanRoy I still do not ser the new release available on maven repository. 
Can you please confirm that this has been published?
Thanks

**Comment by VanRoy** [comment]
Indeed @DanielFran , publication failed. Thanks for your feedback.
I will re-publish soon.
